### ISSUE TITLE
integrate rosetta-cli check:construction in CI

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-core-rosetta-gateway#28]
this is blocked on rosetta-cli not being suitable for this use case

---

rosetta-cli's `check:construction` doesn't have an `--end` flag. it can only create transactions forever. we can't use it for this CI test yet.

_Originally posted by @pro-wh in https://github.com/oasisprotocol/oasis-core-rosetta-gateway/issues/25#issuecomment-669603564_

**Comment by pro-wh** [comment]
https://community.rosetta-api.org/t/feedback-request-automated-construction-api-testing-improvements/146/7?u=oasis-w
reported

**Comment by kostko** [comment]
Done in #31.
