### ISSUE TITLE
intent for reclaim escrow

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-core-rosetta-gateway#29]
currently the intent is such that you reduce the balance in terms of a separate "pool shares" currency. that was just a wild idea not at all grounded in the reality of rosetta's model. we need a design that fits, among others, these properties:

- a transaction must come back through the data API as a superset of the intent
- an account identifier has a fixed currency

it had been done this way with the pool shares in the first place because you don't know for sure what the token worth of the shares will be when the transaction executes.

**Comment by kostko** [comment]
This was done, right?

**Comment by pro-wh** [comment]
oh yeah
