### ISSUE TITLE
correct handling of initial block height>1

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-core-rosetta-gateway#58]
I think oasis-core added support for starting at a height greater than 1. fix up the block API which assumed the initial block is height=1

**Comment by kostko** [comment]
Which part of the Rosetta API assumes that genesis is always at block 1? I think it fetches the genesis block and uses its height? In any case we should at least add a test case for starting with an initial height greater than 1.

**Comment by pro-wh** [comment]
https://github.com/oasisprotocol/oasis-core-rosetta-gateway/blob/7796db554f443fa82a80ae6c7466096d030504e4/oasis-client/oasis-client.go#L25

**Comment by abukosek** [comment]
The assumption used to be in the `rosetta-cli` validator -- the validation failed unless block 1 was available.  Not sure if this was fixed already or not, but it should be verified before we do any changes.
