### ISSUE TITLE
Offline mode that only enables a subset of Construction API

### ISSUE THREAD

**Issue by songchenwen** [oasisprotocol/oasis-core-rosetta-gateway#77]
All construction APIs now begin with a check of `ValidateNetworkIdentifier`. But according to [rosetta doc](https://www.rosetta-api.org/docs/flow.html#construction-api), most of construction APIs should be working offline. 

And we need them to work without `oasisClient` to integrate this project into bitpie wallet. Could you make this `oasisClient` in construction API service optional?

**Comment by kostko** [comment]
Note that only part of the construction API methods can be used offline.
